version: "3.9"
   
services:
  db:
    container_name: django-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres
    networks:
      - django-net
  web:
    container_name: django-web
    build: .
    command: /start
    volumes:
      - .:/django-base
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.django
    depends_on:
      - db
    networks:
      - django-net

networks:
    django-net:
